os: osx
language: node_js
node_js:
  - 14
before_install: cd web
install: 
- yarn install --production=false
- node node_modules/node-sass/scripts/install.js
- ./node_modules/.bin/cypress install
- yarn add cypress-cucumber-preprocessor
script:
- yarn test
- PUBLIC_URL="https://s3.amazonaws.com/chasebox.com/"
- yarn build
deploy:
  provider: s3
  secret_access_key:
    secure: JX1bqY/eb2pyS86ONpqnh+WxpzjO2Q2tR3nsz6PPVTmuW3sgqJI/q7zfj6g9LD+UuRw6aga0wIONi9Qq4UvcKBYRA3peRsWnH+0xMw29URKYDpSJ6lVRD6cA4KQPIsBrsD6sctzLs4VzF0vYEbl1vWjVJn0w91UQL03lEG7ZD1BwF4BqXNl7qL22kJgnpHZUS+xIokePEZVtzSX2siE14ROVL3sEBj6I7DBVljv/AmBXUenf7VHbw/TBqxR78Lg5xz+7a/0fecjwEYVBYuy1FvC9hdifaXAX6oHctnCAKLXQYEOfdQC4+7YhoBP5D4TnY2u7USSv331MYDPV+OJjmgZfXqdrav8Akk+AT4T93gOdB1Kv8bMSHui6ukNdDV66+QpXBoayVeH8MtdIOXAHY4QdcvZJZ5EGOYp+p3/3noRqttUdKwjioPT5IENsqECGwPzr34MKYc3WladKxAZxOjla1kzVsETZNEpXagLoMf9+SRRIxGyvVV8hfUqErRDS6TUmLVxWvn2WJbY3NthyTv4a52dDZb2Wg2Ui30cTChguCl3SfBwpFAK+vEYYJy2CLUrdOZhNBtHPfKi7bBp7N0aMLg354fDfPRZfI6q3Z8X3nOhlp36RbzSgZAIKpulylEh+9vGKXTid5BSeCCpkuH+aTBnvIEclCaD/T30BzG0=
  access_key_id:
    secure: AbVjfUMTrtLVOTShXWzm7D8zi4FsQ6FjYMgU7RVqof5Gl13JH+NfDiZ9hYYqtO9idX+nYwTo8RZcejfqJJVCImAn/p5Y4VsuUPbLjkBfKbSt8DAl/AYxxBTgnQ3vaxX/viRBxjwepvfBugevuWwyyzA+pMq7JqHTEmt+qda9rlGBgSpqXjPeGP8P4cWIYOo9NHr42sHweFX2JcNemg+hfRYiK99uYfX88d2g6pYwBOermz4z/MB3pa47otpURC6p9Y8bjqavKhC4bXhAHrETNrET+cGVv202KhDorrTjYt9juDH9kzD0qf0IYYKkGgyte605MhNypfTQoZayFWuXY1+TSr3CgDqpsyaxnsTD7HCpJ9M/aF6HakJ6PKbEs0aBCk0We9WOWlpEg99OuudAiNs7nrmemFmxNDkqHGGgpde2YoR6HfFAJCWbauBvNZqBFO5uD5UMpREV/xLWhbBZRrMQDUX+xPMZadTr5RdAhiOD23UHdN/sPVSHMN0Hwk9hMz4nye9yZDEHD7/XEvpZXVjnYeRj/pKF7P8KTsDcT/RRBpt1Z4y/7DjIP42OU1l33iSM3yk1R6FngY2MVK+wArZ9L6+W4hhuxHTAZRYelZYhxT5aycNxyP5iHTjgP5om7Y/sgUK2uX3nDZtWT5Ff9UIswR3nm8M0g8rnUWLwV3Q=
  bucket: "chasebox.com"
  acl: public_read
  region: us-east-1
  local_dir: web/build
  cleanup: false